import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Cotizar entrega',
  description: 'Generated by create next app',
}

export default function CotizarLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section className="top-[0px] absolute">
        {children}
    </section>
  )
}
