import { Metadata } from "next"


export const metadata: Metadata = {
  title: 'Cotizar entrega',
  description: 'Generated by create next app',
}

export default  function ConductoresLayout({children,}: { children: React.ReactNode}) {


  return (
    
    <section>
        {children}
    </section>
      
   

  )
}
