import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './provaider'
import Navbar from '@/components/nav/nav'
import Map from '@/components/map/map'
import { GetData } from '@/services/get.data'
import { DeliveryJSON } from './api/delivery/delivery.type'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  const data = await GetData([process.env.DOMAIN+'/api/delivery'])
  .then(res => res[0] as DeliveryJSON);


  return (
    <Providers>
      <html lang="en">
        <body className="w-screen h-screen">
          <Navbar
          logo={JSON.parse(data.body[0].media).img.logo}
          name={JSON.parse(data.body[0].data as string).name}
          items={JSON.parse(data.body[0].data as string).items}
          social={JSON.parse(data.body[0].data as string).social}
          theme={JSON.parse(data.body[0].data as string).theme}
        />
          <Map 
            apiKey={JSON.parse(data.body[0].data as string).apiKeyMaps}  
          />
          {children}
        </body>
      </html>

    </Providers>
    
  )
}
