import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './provaider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: {children: React.ReactNode}) {

  return (
    <Providers>
      
      <html lang="es">
        <body className="w-screen h-screen">
          {children}
        </body>
      </html>

    </Providers>
    
  )
}
