import Map from "@/components/map/map"
import Navbar from "@/components/nav/nav"
import { GetData } from "@/services/get.data";
import { Metadata } from "next"
import { DeliveryJSON } from "../api/delivery/delivery.type";

export const metadata: Metadata = {
  title: 'Cotizar entrega',
  description: 'Generated by create next app',
}

export default async function CoberturaLayout({children,}: { children: React.ReactNode}) {

  const data = await GetData([process.env.DOMAIN+'/api/delivery'])
  .then(res => res[0] as DeliveryJSON);



  return (
    <>
      <Navbar
        logo={JSON.parse(data.body[0].media).img.logo}
        name={JSON.parse(data.body[0].data as string).name}
        items={JSON.parse(data.body[0].data as string).items}
        social={JSON.parse(data.body[0].data as string).social}
        theme={JSON.parse(data.body[0].data as string).theme}
        admin={false}
      />
      <Map 
        apiKey={JSON.parse(data.body[0].data as string).apiKeyMaps}  
      />
      <section>
        {children}
      </section>
      
    </>

  )
}
